name: Deploy Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Pack and Push NuGet Package LNDroneController.LND
      run: |
        cd LNDroneController.LND
        dotnet pack --configuration Release
        cd bin/Release/
        package=$(ls LNDroneController.LND.*.nupkg)
        dotnet nuget push $package  --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
        cd ..
    - name: Pack and Push NuGet Package LNDroneController.CLN
      run: |
        cd LNDroneController.CLN
        dotnet pack --configuration Release
        cd bin/Release/
        package=$(ls LNDroneController.CLN.*.nupkg)
        dotnet nuget push $package  --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
        cd ..